# Generated by Django 4.1 on 2022-09-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil_cuit', models.CharField(max_length=40)),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('domicilio', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=1)),
                ('nombre_apellido', models.CharField(max_length=40)),
                ('cuil_cuit', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('monto_sin_iva', models.IntegerField()),
                ('iva', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=40)),
                ('precio_sin_iva', models.IntegerField()),
                ('iva', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Familiares',
        ),
    ]
