# Generated by Django 4.1 on 2022-11-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0004_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='iva',
            field=models.CharField(max_length=5),
        ),
    ]
