# Generated by Django 4.1 on 2022-11-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0005_productos_imagen_alter_productos_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, max_length=200, null=True, verbose_name='Precio'),
        ),
    ]
