# Generated by Django 4.1 on 2022-11-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0006_productos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=15, max_length=200, verbose_name='Precio'),
        ),
    ]
