# Generated by Django 4.1 on 2022-11-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0008_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
